[package]
name = "kast-ast"
version.workspace = true
edition.workspace = true
description = "ast parser for kast"
license.workspace = true
repository.workspace = true

[dependencies]
kast-util.workspace = true
tracing.workspace = true
noisy_float.workspace = true
decursion.workspace = true
