name: CI
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - runs-on: ubuntu-latest
            name: linux
          - runs-on: macos-latest
            name: macos
          - runs-on: windows-latest
            name: windows
    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: npm ci
      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.4
          dune-cache: true
      - name: Resolve dependencies
        shell: bash
        run: |
          dune pkg lock
      - name: Build project
        shell: bash
        run: |
          dune build
        env:
          KAST_STD: "../lib/std"
      - name: Run tests
        shell: bash
        run: |
          dune runtest
      - name: Collect artifacts
        run: |
          mkdir -p artifacts
      - run: |
          mkdir -p artifacts/kast-js
          cp _build/default/src/kast/js/kast_js.bc.js artifacts/kast_js.bc.js
      - run: |
          PLATFORM="${{ matrix.platform.name }}"
          BIN_NAME=kast
          if [ "$PLATFORM" == "windows"]; then
            BIN_NAME=kast.exe
          fi
          mkdir -p artifacts/$PLATFORM
          mkdir -p artifacts/$PLATFORM/bin
          mkdir -p artifacts/$PLATFORM/lib
          cp _build/default/src/kast/bin/main.exe artifacts/$PLATFORM/bin/$BIN_NAME
          cp -r std artifacts/$PLATFORM/lib/std
          tar -czf artifacts/kast-$PLATFORM.tar.gz -C artifacts/$PLATFORM .
          rm -rf artifacts/$PLATFORM
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-${{ matrix.platform.name }}
          path: artifacts/

  deploy-pages:
    if: github.ref == 'refs/heads/main' && github.repository_owner == 'kast-lang'
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v5
      - name: Upload pages artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: artifacts/
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4